name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create emulator
      run: |
        echo avdmanager create avd -n TestAVD -k "system-images;android-30;google_apis;x86" --device "Pixel_4"

    - name: Start emulator
      run: |
        $ANDROID_HOME/emulator/emulator-avd test -no-skin -no-audio -no-window &

    - name: Print devices
      run: avdmanager list device

    #- name: Print logs
      #run: adb logcat


      
