name: gen time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  bidder-token-gen-time:

    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Run emulator, install & launch app and get logs
      uses: ReactiveCircus/android-emulator-runner@v2
      with: 
        api-level: 30
        target: google_apis
        arch: x86_64
        emulator-options: -no-window -no-audio -no-skin
        script: |
          ./gradlew installDebug
          adb logcat -c
          touch app/emulator.log
          chmod 777 app/emulator.log
          adb logcat com.example.quizapp >> app/emulator.log & 
          adb shell am start -n com.example.quizapp/.MainActivity
          sleep 30
          adb shell am force-stop com.example.quizapp
          adb logcat -c
          touch app/emulator_next.log
          chmod 777 app/emulator_next.log
          adb logcat com.example.quizapp >> app/emulator_next.log & 
          adb shell am start -n com.example.quizapp/.MainActivity
          sleep 30

    - name: Upload logs of cold start
      uses: actions/upload-artifact@v3
      with:
        name: cold_logs
        path: app/emulator.log
    - name: Upload logs of warm start
      uses: actions/upload-artifact@v3
      with:
        name: warm_logs
        path: app/emulator_next.log

    - name: Run script
      run: |
        files=("app/emulator.log" "app/emulator_next.log")
        table_string=""
        for file in $files; do
          start_time=$(grep "Splashscreen#newInstance" $file | awk '{print $2}')
          echo $start_time
          end_time=$(grep "Splashscreen#onAttach" $file | awk '{print $2}')
          echo $end_time
          time_diff=$(awk 'END {
            split(st,a,":");
            sec1=a[1]*3600+a[2]*60+a[3];
            split(ed,b,":");
            sec2=b[1]*3600+b[2]*60+b[3];
            val=sec2-sec1;
            print val }' st=$start_time ed=$end_time)
          table_string+="$time_diff,"
        done
        echo $table_string
