# This workflow will set a number or reviewers depending on the labels
name: Label Reviews
# Trigger the workflow on pull requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action@1.3.0
        env:
          GITHUB_TOKEN: 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
        with:
          rules_yaml: | # define which PR labels require how many aprroving reviewers
            Update: ${{ vars.REVIEWERS }}
  
