# This workflow will set a number or reviewers depending on the labels
name: Label Reviews
# Trigger the workflow on pull requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  require-reviewers:
    # Optional: skip check if no relevant label is present
    # This needs to be kept in sync with the labels being checked
    if: ${{ contains(github.event.pull_request.labels.*.name, '*') || contains(github.event.pull_request.labels.*.name, 'migration') }}
    runs-on: ubuntu-latest
    steps:
      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
