# This workflow will set a number or reviewers depending on the labels
# anything else
name: Label Reviews
# Trigger the workflow on pull requests
# PAT  : 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
#             Update: ${{ vars.REVIEWERS }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: get the count of requested reviewers
        run: |
          length=$(echo $requested_reviewers | jq '. | length')
          echo "length = $length"
        env:
          requested_reviewers: ${{ github.event.pull_request.requested_reviewers }}
