name: Change

on:
  pull_request:
    branches:
      - "*"
    types:
      - closed

jobs:
  my_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
        
      - name: check python file
        run: |
          chmod +x ./.github/scripts/temp.py
          output=$(python3 ./.github/scripts/temp.py ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ${{ github.event.number }})
          
          echo "output: $output"
          echo "$output" >> $GITHUB_STEP_SUMMARY
      
