name: Change

on:
  workflow_dispatch:

jobs:
  my_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: check python file
        run: |
          chmod +x ./.github/scripts/temp.py
          output=python3 ./.github/scripts/temp.py
          echo "output: $output"
          echo "$output" >> $GITHUB_STEP_SUMMARY
      
