name: APK size analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  apk_size_analysis_report_file: apk_size_analyis_report.html
  aar_size_analysis_report_file: aar_size_analysis_report.html
  all_reports_file: all_reports.html
  

jobs:
  apk_build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to head branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Gradle & Android SDK Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            /usr/local/lib/android/sdk/build-tools
            /usr/local/lib/android/sdk/system-images
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # - name: Set the variables
      #   run: |
      #     echo "{old_apk_size}={0}" >> $GITHUB_ENV
      #     echo "{new_apk_size}={0}" >> $GITHUB_ENV

      - name: Build release APK
        run: |
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/release-base-apk.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-base-apk.apk
          path: app/build/outputs/apk/release/release-base-apk.apk

      - name: Build release APK for ARM64_V8A
        run: |
          ./gradlew assembleRelease -PtargetAbi=arm64-v8a
          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk

      - name: Upload release APK for ARM64_V8A
        uses: actions/upload-artifact@v3
        with:
          name: release-base-arm64-v8a-apk.apk
          path: app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk

      - name: Run python script
        run: |
          chmod +x ./.github/scripts/temp.py
          python3 ./.github/scripts/temp.py

      - name: Print the variables
        id: variable_print
        run: |
          echo "old-size: ${{ env.old_apk_size }}"
          echo "new-size: ${{ env.new_apk_size }}"

      # - name: Merge files
      #   run: |
      #     echo "print value"
          
      #     if [ ${{ steps.variable_print.outcome }} = 'success' ]
      #     then
      #       echo "success"
      #     else
      #       echo "failure"
      #     fi
      #     cat ${{ env.apk_size_analysis_report_file }} ${{ env.aar_size_analysis_report_file }} > ${{ env.all_reports_file }}


  pr_comment_of_all_reports:
    if: ${{ always() }}
    name: Add PR comment containing all reports
    runs-on: ubuntu-latest
    steps:
      - name: Download apk_size_analysis_report_file
        id: download_apk_size_analysis_report_file
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.apk_size_analysis_report_file }}

      - name: Download aar_size_analysis_report_file
        id: download_aar_size_analysis_report_file
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.aar_size_analysis_report_file }}

      - name: Merge all reports in all_reports_file
        run: |
          if [ steps.download_apk_size_analysis_report_file.outcome = 'success' ] && [ steps.download_aar_size_analysis_report_file.outcome = 'success' ]
          then
            cat ${{ env.apk_size_analysis_report_file }} ${{ env.aar_size_analysis_report_file }} > ${{ env.all_reports_file }}
          elif [ steps.download_apk_size_analysis_report_file.outcome = 'success' ]
          then
            cat ${{ env.apk_size_analysis_report_file }} > ${{ env.all_reports_file }}
          elif [ steps.download_aar_size_analysis_report_file.outcome = 'success' ]
          then
            cat ${{ env.download_aar_size_analysis_report_file }} > ${{ env.all_reports_file }}
          fi
        
      - name: A/B check
        uses: actions/github-script@v6
        with:
          script: |
              const fs = require('fs')
              const filePath = 'all_reports.html'
              const sizeReportContent = fs.readFileSync(filePath, 'utf8')
              console.log("sizeReportContent: ",sizeReportContent)
        
      
