name: APK size analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  apk_size_analysis_report_file: apk_size_analyis_report.html

jobs:
  apk_build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        myVariable: ["","arm64-v8a","armeabi-v7a","x86","x86_64"]

    steps:
      - name: Checkout to head branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Gradle & Android SDK Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            /usr/local/lib/android/sdk/build-tools
            /usr/local/lib/android/sdk/system-images
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build release APK
        run: |
          ./gradlew assembleRelease -PtargetAbi=${{ matrix.myVariable }}
          echo "myVariable: ${{ matrix.myVariable }}"
          if [ ${{ matrix.myVariable }} != "" ]
          then 
            mv app/build/outputs/apk/release/app-${{ matrix.myVariable }}-release-unsigned.apk app/build/outputs/apk/release/release-base-apk-${{ matrix.myVariable }}.apk
          else
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/release-base-apk.apk
          fi

      # - name: getFile name
      #   id: getName
      #   with:
      #     cond: ${{ matrix.myVariable != '' }} 
      #     if_true: release-base-apk-${{ matrix.myVariable }}.apk
      #     if_false: release-base-apk.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getName.outputs.value }}
          path: app/build/outputs/apk/release/release-base-apk-${{ steps.getName.outputs.value }}

      # - name: Build release APK for ARM64_V8A
      #   run: |
      #     ./gradlew assembleRelease -PtargetAbi=arm64-v8a
      #     mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk

      # - name: Upload release APK for ARM64_V8A
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-base-arm64-v8a-apk.apk
      #     path: app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk
        
      
