name: APK size analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  apk_size_analysis_report_file: apk_size_analyis_report.html

jobs:
  apk_build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        myVariable: ["","arm64-v8a","armeabi-v7a","x86","x86_64"]

    steps:
      - name: Checkout PR base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Gradle & Android SDK Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            /usr/local/lib/android/sdk/build-tools
            /usr/local/lib/android/sdk/system-images
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build release base APK
        run: |
          ./gradlew assembleRelease -PtargetAbi=${{ matrix.myVariable }}
          echo "myVariable: ${{ matrix.myVariable }}"
          if [ ${{ matrix.myVariable }} != "" ]
          then 
            mv app/build/outputs/apk/release/app-${{ matrix.myVariable }}-release-unsigned.apk app/build/outputs/apk/release/release-base-apk-${{ matrix.myVariable }}.apk
          else
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/release-base-apk.apk
          fi

      - name: getFile name for base
        uses: haya14busa/action-cond@v1
        id: getNameBase
        with:
          cond: ${{ matrix.myVariable != '' }} 
          if_true: release-base-apk-${{ matrix.myVariable }}.apk
          if_false: release-base-apk.apk

      - name: Upload release APK for base branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getNameBase.outputs.value }}
          path: app/build/outputs/apk/release/${{ steps.getName.outputs.value }}

      - name: Build debug APK for base branch
        run: |
          ./gradlew app:assemble -PtargetAbi=${{ matrix.myVariable }}
          if [ ${{ matrix.myVariable }} != "" ]
          then
            mv app/build/outputs/apk/debug/app-${{ matrix.myVariable }}-debug.apk app/build/outputs/apk/debug/debug-base-apk-${{ matrix.myVariable }}.apk
          else
            mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/debug-base-apk.apk
          fi

      - name: Debug APK name on base branch
        uses: haya14busa/action-cond@v1
        id: debugBaseApkName
        with:
          cond: ${{ matrix.myVariable != '' }}
          if_true: debug-base-apk-${{ matrix.myVariable }}.apk
          if_false: debug-base-apk.apk

      - name: Upload debug base APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.debugBaseApkName.outputs.value }}
          path: app/build/outputs/apk/debug/${{ steps.debugBaseApkName.outputs.value }}

      - name: Checkout PR head branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch_depth: 0

      - name: Build release head APK
        run: |
          ./gradlew assembleRelease -PtargetAbi=${{ matrix.myVariable }}
          echo "myVariable: ${{ matrix.myVariable }}"
          if [ ${{ matrix.myVariable }} != "" ]
          then 
            mv app/build/outputs/apk/release/app-${{ matrix.myVariable }}-release-unsigned.apk app/build/outputs/apk/release/release-head-apk-${{ matrix.myVariable }}.apk
          else
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/release-head-apk.apk
          fi

      - name: getFile name for head
        uses: haya14busa/action-cond@v1
        id: getNameHead
        with:
          cond: ${{ matrix.myVariable != '' }} 
          if_true: release-head-apk-${{ matrix.myVariable }}.apk
          if_false: release-head-apk.apk

      - name: Upload release APK for head branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.getNameHead.outputs.value }}
          path: app/build/outputs/apk/release/${{ steps.getNameHead.outputs.value }}

      - name: Build debug APK for head branch
        run: |
          ./gradlew app:assemble -PtargetAbi=${{ matrix.myVariable }}
          if [ ${{ matrix.myVariable }} != "" ]
          then
            mv app/build/outputs/apk/debug/app-${{ matrix.myVariable }}-debug.apk app/build/outputs/apk/debug/debug-head-apk-${{ matrix.myVariable }}.apk
          else
             mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/debug-head-apk.apk
          fi

      - name: Debug APK name on head branch
        uses: haya14busa/action-cond@v1
        id: debugHeadApkName
        with:
          cond: ${{ matrix.myVariable != '' }}
          if_true: debug-head-apk-${{ matrix.myVariable }}.apk
          if_false: debug-head-apk.apk

      - name: Upload debug head APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.debugHeadApkName.outputs.value }}
          path: app/build/outputs/apk/debug/${{ steps.debugHeadApkName.outputs.value }}

  apk_report:
    name: APK report
    needs: apk_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release-base-apk.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-base-apk-arm64-v8a.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-base-apk-armeabi-v7a.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-base-apk-x86_64.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-base-apk-x86.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-head-apk.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-head-apk-arm64-v8a.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-head-apk-armeabi-v7a.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-head-apk-x86_64.apk

      - uses: actions/download-artifact@v3
        with:
          name: release-head-apk-x86.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-base-apk.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-base-apk-arm64-v8a.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-base-apk-armeabi-v7a.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-base-apk-x86_64.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-base-apk-x86.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-head-apk.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-head-apk-arm64-v8a.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-head-apk-armeabi-v7a.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-head-apk-x86_64.apk

      - uses: actions/download-artifact@v3
        with:
          name: debug-head-apk-x86.apk

      - name: Generate APK Size Report
        run: |
          chmod +x ./.github/scripts/compare.py
          python3 ./.github/scripts/compare.py "release-base-apk" "release-head-apk" "release-base-apk-arm64-v8a" "release-head-apk-arm64-v8a"
          "release-base-apk-arm64-v8a" "release-head-apk-arm64-v8a" "release-base-apk-armeabi-v7a" "release-head-apk-armeabi-v7a"
          # "release-base-apk-x86_64" "release-head-apk-x86_64" "release-base-apk-x86" "release-head-apk-x86"
          # "debug-base-apk-arm64-v8a" "debug-head-apk-arm64-v8a" "debug-base-apk-armeabi-v7a" "debug-head-apk-armeabi-v7a"
          "debug-base-apk-x86_64" "debug-head-apk-x86_64" "debug-base-apk-x86" "debug-head-apk-x86"
    
      
