name: APK size analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  apk_size_analysis_report_file: apk_size_analyis_report.html

jobs:
  apk_size_analysis:
    uses: ./.github/workflows/artifact-producer.yml
    
  outputs_reading:
    uses: ./.github/workflows/outputs-producer.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [apk_size_analysis]

    steps:
    
    - name: Upload release APK for ARM64_V8A
      uses: actions/download-artifact@v3
      with:
        name: release-base-arm64-v8a-apk.apk
        path: app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk

    # - name: reading output from a reusable workflows
    #   run: |
    #    echo "printing from main.yml"
    #    echo ${{ needs.outputs_reading.outputs.answer }}

  # read_ops:
  #   runs-on: ubutu-latest
  #   needs: [outputs_reading]
  #   steps:
  #   - name: reading output from a reusable workflows
  #     run: |
  #      echo "printing from main.yml"
  #      echo ${{ needs.outputs_reading.outputs.answer }}
