name: APK size analysis

on:
  pull_request:
    branches:
      - '*'
    types:
      - closed

env:
  analysis_report_file: analyis_report.html

jobs:
  apk_size_analysis:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/artifact-producer.yml
    
  outputs_reading:
    uses: ./.github/workflows/outputs-producer.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [apk_size_analysis, outputs_reading]

    steps:
    
    - name: Upload release APK for ARM64_V8A
      uses: actions/download-artifact@v3
      with:
        name: release-base-arm64-v8a-apk.apk
        path: app/build/outputs/apk/release/release-base-arm64-v8a-apk.apk

    - name: reading output from a reusable workflows
      run: |
       echo "printing from main.yml"
       echo ${{ needs.outputs_reading.outputs.answer }}

  pr_comment:
    name: Add PR comment
    runs-on: ubuntu-latest

    steps:
      - name: frame html file
        id: frame_html
        run: |
          echo "<html><body><h2> html file</h2></body></html>" >> ${{ env.analysis_report_file }}

      - name: Add PR comment
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const filePath = 'analyis_report.html'
              const reportContent = fs.readFileSync(filePath)
              const result = await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: reportContent
              })
              console.log(result)
            }
            catch(e) {
              console.error("Error reading file: ", e);
            }
  
